security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\Swimmer
                property: email  

    firewalls:
        main:
           
            form_login:
                login_path: login  
                check_path: login  
                default_target_path: /  
            logout:
                path: logout 
                target: /login  

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }